### PR TITLE
[WIP] Merge spans longer than 3 reserved sections

### PR DESCRIPTION
**Pull request by vrajmohan**
Identify these spans by the starting section number. Update the section
title to indicate the sections in the span.

### CODE REVIEW

**Comment by vrajmohan** [comment]
Question: Is there ever a span of sections that are not _RESERVED_?

**Comment by cmc333333** [comment]
This looks good!

Looks like test failures are integration tests for FEC and EPA, which probably both have runs of > 3 reserved sections. Would you mind verifying the data on FEC and I'll take a look at EPA?

> 1. Is there ever a span of sections that are not RESERVED?

Good question -- we haven't seen any that weren't reserved across the four eRegs agencies, so I think that's a safe bet now.

> 2. Should the span indicator be explicit rather than implicit in the title?

I don't follow; would you mind giving an example?

**Comment by vrajmohan** [comment]
I'll verify the integration test failures for FEC.

**Comment by vrajmohan** [comment]
Should the span indicator be explicit rather than implicit in the title?

In https://github.com/eregs/regulations-parser/blob/767aa18e7f5d8297c6ddc268ab079d8f37dcc09a/regparser/tree/xml_parser/reg_text.py#L256, we already know that we are dealing with sections and/or section spans. We don't indicate this information _explicitly_ in the persisted output. It is _implicit_ in the `label` and the `title`. In https://github.com/eregs/regulations-site/blob/23fd2ab001782a9654e26496aa96870d16b71614/regulations/generator/title_parsing.py#L40, we extract this information again using similar logic.

**Comment by cmc333333** [comment]
@vrajmohan gotcha. I think they're working slightly different angles. The `build_from_section` logic is meant to only concern itself with the creation of `Node` objects, so it cares about spans of sections only to the extent that it needs to create multiple `Node`s or not. We're doing a bit of reformatting there, but I think that's more out of convenience than cleanliness.

I don't think that section-spanning data is very important to `Node`s; but it _is_ important to the table-of-contents layer. I'd argue that it _should_ be explicit there. Unfortunately the relevant logic is actually within -site :(. We run into a similar problem in the [N&C code](https://github.com/eregs/regulations-site/blob/aa8140670477810085b91d6e7eede33259d1234c/fr_notices/navigation.py#L61) -- it'd be ideal if the _parser_ was doing the parsing rather than the UI.

**Comment by cmc333333** [comment]
I can confirm that the only changes to EPA are expected -- several runs of sections are merged into a single "reserved" section.

**Comment by vrajmohan** [comment]
Likewise, I can confirm that the only changes to FEC are expected -- several runs of sections are merged into a single "reserved" section.

**Comment by cmc333333** [comment]
Looks good, test failures make sense, and @vrajmohan assures this is no longer a WIP

**Pull request merged**
