### PR TITLE
Add a preorder index to the persisted node

### PR DESCRIPTION
**Pull request by vrajmohan**
This helps sort the nodes during display

### CODE REVIEW

**Comment by cmc333333** [comment]
This makes sense and we should expect the integration tests to fail (as the output JSON is being modified). A few things that we might need to do before merging:

1. A test to verify the order would be helpful
2. We'll want to make the same transform in `write_preambles`
3. I _think_ this breaks writes to the API, which validates against a [schema](https://github.com/eregs/regulations-core/blob/master/regcore_write/views/document.py#L11). We can either modify that schema or remove it entirely.

**Comment by vrajmohan** [comment]
Good catch on `write_preambles`.
I'll plan on updating the JSON schema used to validate the _write_.

**Comment by vrajmohan** [comment]
We could either make `preorder_idx` a required field in the JSON schema, or, make it optional and handle its absence gracefully. I am inclined to the former. Other opinions?

**Comment by cmc333333** [comment]
Looks great!

**Pull request merged**
