### PR TITLE
Make preamble intro separate paragraphs.

### PR DESCRIPTION
**Pull request by tadhg-ohiggins**

### CODE REVIEW

**Comment by tadhg-ohiggins** [comment]
Missed this test, my apologies. Fixing in progress.

**Comment by tadhg-ohiggins** [comment]
I'm not sure about the labels here, but it should be easy to change them if necessary.

**Comment by cmc333333** [comment]
Looks good. Would you mind adding a test for the specific scenario of having multiple paragraphs in one of these sections? Could just modify the existing test, too.

**Comment by tadhg-ohiggins** [comment]
Test tweaked; I'm assuming it's okay for the the test document to have two SUMMARY elements.

**Comment by cmc333333** [comment]
Good stuff

**Pull request merged**
